[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ga-tests"
version = "0.1"
dependencies = ["pytest"]
requires-python = ">=3.8"

[tool.hatch.build.targets.wheel]
packages = ["tests"]
