name: Tests

on: [push, pull_request]

env:
  PY_COLORS: 1
  COLUMNS: 110
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:

  lint:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: false
      - name: Run tests with ${{ matrix.python-version }}
        run: uv run --with pytest --python ${{ matrix.python-version }} -- pytest
