name: Tests

on: [push, pull_request]

env:
  PY_COLORS: 1
  COLUMNS: 110
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:

  macos-x86_64:
    runs-on: macos-13
    steps:
      - name: Build
        run: |
          git clone https://github.com/MSLNZ/msl-nlf.git
          g++ -shared -Bstatic -fPIC msl-nlf/docs/assets/Nelson.cpp -o Nelson_x64.dylib
          g++ -shared -Bstatic -fPIC msl-nlf/docs/assets/Roszman1.cpp -o Roszman1_x64.dylib
          cp Roszman1_x64.dylib Roszman1_x64_copy.dylib
      - name: Upload libraries
        uses: actions/upload-artifact@v4
        with:
          name: macos-x86_64
          path: "*.dylib"

  macos-arm64:
    runs-on: macos-14
    steps:
      - name: Clone
        run: |
          git clone https://github.com/MSLNZ/msl-nlf.git
          g++ -shared -Bstatic -fPIC msl-nlf/docs/assets/Nelson.cpp -o Nelson_arm64.dylib
          g++ -shared -Bstatic -fPIC msl-nlf/docs/assets/Roszman1.cpp -o Roszman1_arm64.dylib
          cp Roszman1_arm64.dylib Roszman1_arm64_copy.dylib
      - name: Upload libraries
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64
          path: "*.dylib"
