name: Tests

on: [push, pull_request]

env:
  PY_COLORS: 1
  COLUMNS: 110
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      MYPYPATH: src
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false
      - name: Install cSpell
        run: npm install -g cspell@latest
      - name: Spelling
        run: cspell .
      - name: Linting
        run: uv run -- ruff check --force-exclude --no-fix .
      - name: Formatting
        run: uv run -- ruff format --force-exclude --check .
      - name: Typing:BasedPyright
        run: uv run --with comtypes -- basedpyright .
      - name: Typing:MyPy
        run: uv run -- mypy .
