name: Tests

on: [push, pull_request]

env:
  PY_COLORS: 1
  COLUMNS: 110
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Clone
        run: git clone https://github.com/MSLNZ/msl-nlf.git
      - name: ldd
        run: |
          ldd msl-nlf/tests/user_defined/Nelson_x64.so
          ldd msl-nlf/tests/user_defined/Roszman1_x64.so
      - name: Install package
        run: |
          cd msl-nlf
          pip install .[tests]
      - name: Compile Roszman1
        run: |
          g++ -shared -Bstatic msl-nlf/docs/assets/Roszman1.cpp -o Roszman1_x64.so
      - name: Run tests
        run: |
          ls -la
          python -m pytest tests