name: Tests

on: [push]

env:
  PY_COLORS: 1
  COLUMNS: 110

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os : [ubuntu-24.04-arm]
        # os: [macos-latest, ubuntu-22.04, windows-latest]
        # python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      # - name: Install uv
      #   uses: astral-sh/setup-uv@v6
      #   with:
      #     enable-cache: false
      # - name: Run tests with ${{ matrix.python-version }}
      #   run: uv run --python ${{ matrix.python-version }} -- pytest
      - name: Build linux
        if: ${{ matrix.os == 'ubuntu-24.04-arm' }}
        run: |
          python3 -c "import sysconfig; print(sysconfig.get_platform())"
          g++ cpp_lib.cpp -fPIC -shared -Wall -o cpp_libaarch64.so
          gfortran -fno-underscoring -fPIC fortran_lib.f90 -static -shared -o fortran_libaarch64.so
      - uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: ${{ matrix.os }}

          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: "*.so"