name: Tests

on: [push, pull_request]

env:
  PY_COLORS: 1
  COLUMNS: 120

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest]
        architecture: [x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: Update PyPI and GitHub caches
        env:
          MSL_PM_GITHUB_AUTH: ${{ secrets.MSL_PM_GITHUB_AUTH }}
          ANOTHER_VARIABLE: ${{ vars.ANOTHER_VARIABLE }}
        run: |
          python -c "import os; print(os.environ.get('MSL_PM_GITHUB_AUTH'))"
          python -c "import os; print(os.environ.get('ANOTHER_VARIABLE'))"
          echo "MSL_PM_GITHUB_AUTH : $MSL_PM_GITHUB_AUTH"
          echo "ANOTHER_VARIABLE   : $ANOTHER_VARIABLE"
