name: Tests

on: [push, pull_request]

env:
  PY_COLORS: 1
  COLUMNS: 110

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        # os: [windows, ubuntu, macos]
        # python-version: ["3.12"]
        # architecture: [x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Compile fortran example
        run: |
          gfortran-13 -fno-underscoring -fPIC fortran_lib.f90 -shared -o fortran_libarm64.dylib
          otool -L fortran_libarm64.dylib
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: "*.dylib"
#      - name: Set up Python ${{ matrix.python-version }}
#        uses: actions/setup-python@v5
#        with:
#          python-version: ${{ matrix.python-version }}
#          # architecture: ${{ matrix.architecture }}
#      - name: Install packages
#        run: |
#          python -m pip install --upgrade pip
#          python -m pip install --upgrade setuptools wheel
#          python -m pip install --upgrade pythonnet pytest
#          python -m pip install git+https://github.com/MSLNZ/msl-equipment.git@main
#      - name: Mono version
#        run: mono --version
#      - name: Dotnet version
#        run: dotnet --version
#      - name: Install package
#        run: python -m pip install --upgrade --prefer-binary --editable .[tests]
#      - name: Echo localhost
#        if: ${{ matrix.os == 'macos' }}
#        run: |
#          cat /etc/hosts
#          echo "HOSTNAME=$HOSTNAME"
#          echo "HOST=$HOST"
#          # echo 127.0.0.1 $HOSTNAME >> /etc/hosts
#      - name: Run ifconfig
#        if: ${{ matrix.os != 'windows' }}
#        run: |
#          ifconfig | grep "inet "
#      - name: Run tests
#        run: python -m pytest -sv
