name: Tests

on: [push]

env:
  PY_COLORS: 1
  COLUMNS: 110

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-2022, windows-latest]
        # python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      # - name: Install uv
      #   uses: astral-sh/setup-uv@v6
      #   with:
      #     enable-cache: false
      # - name: Run tests with ${{ matrix.python-version }}
      #   run: uv run --python ${{ matrix.python-version }} -- pytest
      - name: Build linux
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: g++ gpib.cpp -fPIC -shared -Bstatic -Wall -o gpib.so
      - name: Build macos
        if: ${{ matrix.os == 'macos-latest' }}
        run: g++ gpib.cpp -fPIC -shared -Bstatic -Wall -o gpib.dylib
      - name: Build macos
        if: ${{ matrix.os == 'windows-latest' }}
        run: g++ gpib.cpp -fPIC -shared -Bstatic -Wall -o gpib.dll
      - uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: ${{ matrix.os }}

          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: gpib.*